### ISSUE TITLE
Bug: Pressed `gg` to in a loaded channel

### ISSUE THREAD

**Issue by 1egoman** [1egoman/slick#17]
```
panic: runtime error: index out of range [recovered]
  panic: runtime error: index out of range

goroutine 61 [running]:
main.main.func1.1(0x15bf1a0, 0xc420080840)
  /home/ubuntu/.go_project/src/github.com/1egoman/slick/main.go:48 +0x7a
panic(0x13b1080, 0x15e3090)
  /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/1egoman/slick/gateway.(*PrintableMessage).Lines(0xc4206a7b40, 0xbb, 0xc4206a7b40, 0xc4206a7e88, 0x0)
  /home/ubuntu/.go_project/src/github.com/1egoman/slick/gateway/printable_message.go:98 +0x5c5
github.com/1egoman/slick/frontend.(*TerminalDisplay).DrawMessages(0xc42013c010, 0xc42021c000, 0x64, 0x8b, 0x0, 0x5c, 0xc4206a7e88, 0xc420015c20, 0x1396980)
  /home/ubuntu/.go_project/src/github.com/1egoman/slick/frontend/draw_messages.go:289 +0x41b
main.render(0xc4200ca500, 0xc42013c010)
  /home/ubuntu/.go_project/src/github.com/1egoman/slick/render.go:39 +0x1d4
main.keyboardEvents(0xc4200ca500, 0xc42013c010, 0x15bf1a0, 0xc420080840, 0xc4200e2480)
  /home/ubuntu/.go_project/src/github.com/1egoman/slick/keyboard_events.go:691 +0xab
main.main.func1(0x15bf1a0, 0xc420080840, 0xc4200ca500, 0xc42013c010, 0xc4200e2480)
  /home/ubuntu/.go_project/src/github.com/1egoman/slick/main.go:51 +0x87
created by main.main
  /home/ubuntu/.go_project/src/github.com/1egoman/slick/main.go:52 +0x414
```

**Comment by 1egoman** [comment]
Fixed by e55b6656e394167fccc134915a522eacabd1f1b9

When a message wrapped across multiple lines and there were zero-words to wrap, the code would explode since zero words to wrap would be an an empty array, and we were getting the last element in that array with `a[len(a) - 1`.
